# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvissuperui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.jarvisbg = QtWidgets.QLabel(self.centralwidget)
        self.jarvisbg.setGeometry(QtCore.QRect(4, 0, 2000, 900))
        self.jarvisbg.setText("")
        self.jarvisbg.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\Jarvis1.0\\jarvisui\\images\\jarvisgif.gif"))
        self.jarvisbg.setScaledContents(True)
        self.jarvisbg.setObjectName("jarvisbg")
        self.startlabel = QtWidgets.QLabel(self.centralwidget)
        self.startlabel.setGeometry(QtCore.QRect(1640, 790, 131, 51))
        self.startlabel.setText("")
        self.startlabel.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\Jarvis1.0\\jarvisui\\images\\Start.png"))
        self.startlabel.setScaledContents(True)
        self.startlabel.setObjectName("startlabel")
        self.stoplabel = QtWidgets.QLabel(self.centralwidget)
        self.stoplabel.setGeometry(QtCore.QRect(1790, 790, 131, 51))
        self.stoplabel.setText("")
        self.stoplabel.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\Jarvis1.0\\jarvisui\\images\\Stop.png"))
        self.stoplabel.setScaledContents(True)
        self.stoplabel.setObjectName("stoplabel")
        self.startpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startpushButton.setGeometry(QtCore.QRect(1640, 790, 131, 51))
        self.startpushButton.setStyleSheet("background-color:transparent;\n"
"border:none;")
        self.startpushButton.setText("")
        self.startpushButton.setObjectName("startpushButton")
        self.stoppushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stoppushButton.setGeometry(QtCore.QRect(1790, 790, 131, 51))
        self.stoppushButton.setStyleSheet("background-color:transparent;\n"
"border:none;")
        self.stoppushButton.setText("")
        self.stoppushButton.setObjectName("stoppushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
